#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=100gb,walltime=00:45:00
#PBS -N pRF
#PBS -V

#export MAXMEM=19000000
fmri=$(jq -r .fmri config.json)
stim=$(jq -r .stim config.json)
fsdir=$(jq -r .output config.json)

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -f $(jq -r .mask config.json) ]; then
  time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 bash -c "mri_convert ${fsdir}/mri/T1.mgz ./T1.nii.gz && \
							mri_convert ${fsdir}/mri/rh.ribbon.mgz ./rh.ribbon.nii.gz && \
							mri_convert ${fsdir}/mri/lh.ribbon.mgz ./lh.ribbon.nii.gz && \
							export SUBJECTS_DIR=./ && \
							mri_vol2vol --mov lh.ribbon.nii.gz --targ ${fmri} --interp nearest --regheader --o lh.ribbon.fmri.nii.gz && \
							mri_vol2vol --mov rh.ribbon.nii.gz --targ ${fmri} --interp nearest --regheader --o rh.ribbon.fmri.nii.gz"
  time singularity exec -e docker://brainlife/fsl:5.0.9 ./create_mask_new.sh $fmri
fi

mkdir -p prf

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_vtks.sh $fsdir
